### ISSUE TITLE
White Background

### ISSUE THREAD

**Issue by mxfeinberg** [chasemc/electricShine#103]
When I try to use electricShine, the resulting application just has a white background.

I developed and properly packaged my app and installed it locally.  It's called BTC and I'm able to run this ShinyApp with `BTC::runBTC()`.  I then use electricShine by doing the follow.

`buildPath <- paste(getwd(), "/electricShine", sep="")
MRANdate <- as.character(Sys.Date() - 3)

electricShine::buildElectricApp(
  appName = "BTC",                  # This is what the app/desktop shortcuts will be named on installation.
  description = "BTC Test Application", # Short description when installer is run, etc.
  packageName = "BTC",             # The name of the R package that contains your shiny app.
  semanticVersion = "0.0.1",           # You app's version
  buildPath = buildPath,               # Where the app will build to on your computer.
  MRANdate = MRANdate,                 # The MRAN snapshot date R and R packages will be downloaded from.
  functionName = "runBTC",            # The function name in your app that starts your shiny app.
  githubRepo = NULL,      # GitHub of your R package
  localPath  = "C:\\Users\\Max Feinberg\\Documents\\R\\win-library\\3.6\\BTC", # Alternate to GitHub you can use an R package at a local path
  only64 = TRUE                        # Set to TRUE, this will be deprecated.
)`

Everything seems to execute succesfully and I get this message.

`You should now have both a transferable and distributable installer Electron app.
Warning message:
package ‘C:\Users\Max Feinberg\Documents\R\win-library\3.6\BTC’ is not available (as a binary package for R version 3.6.0)`

Do you have any idea what might be the issue?

![image](https://user-images.githubusercontent.com/7530298/64833663-6fe2d400-d5a4-11e9-81d4-5ed61fed51b0.png)

**Comment by chasemc** [comment]
I've put a bunch of work into a new version after recent feedback (https://github.com/chasemc/electricShine/tree/majorchanges) so won't make changes yet as that merge will come very soon. 


What you can do in the meantime is try the following. (I tested this locally just now, but still could have issues)

```
remotes::install_github("chasemc/electricShine@53e36e0")

buildPath <- tempdir()
MRANdate <- as.character(Sys.Date() - 3)

electricShine::buildElectricApp(app_name = "BTC",
                                product_name = "BTC Test Application",
                                short_description = "test desc",
                                semantic_version = "0.0.1",
                                build_path = buildPath,
                                mran_date = MRANdate,
                                cran_like_url = NULL,
                                function_name = "runBTC",
                                git_host = NULL,
                                git_repo = NULL,
                                local_package_path = "C:\Users\Max Feinberg\Documents\R\win-library\3.6\BTC",
                                package_install_opts = NULL,
                                run_build = TRUE)

```

**Comment by mxfeinberg** [comment]
Thank you so much for getting back to me!  After some small tweaking, I was able to get the app to work.  But then I ran into this issue:

`Uncaught TypeError: Cannot read property 'readyState' of null shinyapp.js:288

at ShinyApp.$sendMsg (shinyapp.js:288)
at ShinyApp.sendInput (shinyapp.js:288)
at InputBatchSender.$sendNow (input_rate.js:220) `

I also found this when google searching: https://github.com/virtualstaticvoid/heroku-buildpack-r/issues/97

**Comment by mxfeinberg** [comment]
It seems to be an issue with a specific library- 
![image](https://user-images.githubusercontent.com/7530298/65074130-cc097780-d959-11e9-8ac4-62860c5b1863.png)

I'm going to try to remove the dependence on this library.

**Comment by mxfeinberg** [comment]
As a note for other people, the white screen that came up before was a result of improperly packaging the Shiny app in a package format.

**Comment by chasemc** [comment]
White screen (https://github.com/chasemc/electricShine/issues/103#issuecomment-532440832):
  - Creating R packages isn't super-hard but it's not trivial. If users are new to making packages, I suggest using  {golem} https://github.com/ThinkR-open/golem .  Note that you will need to add a `port` argument to the package's `run_app` function: see https://github.com/ThinkR-open/golem/issues/128 (I'll try to add this to and make it  clearer how to do this within the {electricShine} documentation)

As for: https://github.com/chasemc/electricShine/issues/103#issuecomment-532372928
  - shinyBS is probably not the issue, as I use it in the app I primarily wrote and use electricShine for
    - Do you have a minimal reproducible example of the app that doesn't work and you can share?

**Comment by mxfeinberg** [comment]
@chasemc 
> As for: [#103 (comment)](https://github.com/chasemc/electricShine/issues/103#issuecomment-532372928)
> 
> * shinyBS is probably not the issue, as I use it in the app I primarily wrote and use electricShine for
>   
>   * Do you have a minimal reproducible example of the app that doesn't work and you can share?

As soon as I removed the dependency on shinyBS, the app worked as expected.   Are you using the CRAN version of shinyBS?  The error seems to be with the shinyBS.css file which on the CRAN version appears to be present but empty.

Thank you for the help!

I have one note, the only issue that I ran into with the package had to do with scenarios where System commands are sent for executable verification.  On windows machines where directories may have spaces, the R system command just uses the directory string while Window's expects quotation marks around the directory name string that contains a space.  In my case something like `C:/Users/Max Feinberg/.../node.exe` instead of `C:/Users/"Max Feinberg"/.../node.exe`.  This can be remedied by splitting the directory on the slashes and adding quotation marks around all substrings that contain spaces.  I'd be happy to submit a PR or you can add it if you'd like.

**Comment by chasemc** [comment]
I appreciate the offer for the fix but I have fixed it locally a few days ago and but got busy and haven't pushed it t GitHub yet. As a note, R has a function to handle this:
https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/shQuote

**Comment by mxfeinberg** [comment]
Oh neat! Thanks for sharing and thank you again for making an excellent package!
