### ISSUE TITLE
add a parameter to install bioconductor packages

### ISSUE THREAD

**Issue by wydty** [chasemc/electricShine#257]
Could you add a parameter to install bioconductor packages for electrify。
Because my app dependency package is not in cran。

`BiocManager::install('seqcombo')`
https://bioconductor.org/install/

Thank you. It was great

**Comment by chasemc** [comment]
Add biocviews to your description file and it should work. For an example see:

https://github.com/chasemc/mzPlotter/blob/c839d1d34ceb91fee4e6e5aa23aceccdb14c3776/DESCRIPTION#L12
