### ISSUE TITLE
How to read files in app?

### ISSUE THREAD

**Issue by bianchenhao** [chasemc/electricShine#271]
The app can normally run when I use `read.csv(here::here("file.csv"))`.

But, it can't correctly read files when I use electricShine to Create Installable Shiny Apps.

How to solve it?

**Comment by chasemc** [comment]
I'm not sure in what context your "file.csv" is used. 

If it is something that is used internally within the app, you will need to include it like you include data within a package, see: http://r-pkgs.had.co.nz/data.html

If it is user-input you can use:https://shiny.rstudio.com/reference/shiny/latest/fileInput.html

**Comment by bianchenhao** [comment]
Thanks! I use `usethis::use_data` successfully run app locally, but as mentioned by [#272 ](https://github.com/chasemc/electricShine/issues/272) I also want to install R 3.6 to create Installable app.

**Comment by chasemc** [comment]
Awesome, I'm going to close this issue and follow up in #272
