### ISSUE TITLE
Allow specified R version in `electrify()` and `install_r()`

### ISSUE THREAD

**Issue by gorcha** [chasemc/electricShine#272]
Currently `electrify()` always installs the most recent version of R on Windows, and uses a hard coded version for Mac.

It'd be great if there were an option allowing the user to specify the R version in `electrify()` or `install_r()`.

**Comment by bianchenhao** [comment]
I'm troubled by this too!

**Comment by chasemc** [comment]
I've added an argument that lets you specify the url to the mac tar.gz and will merge it in when it passes checks.

The versioning with Windows was meant to be achieved by using MRAN to keep R and package installation in sync by specifying a date, that will install packages available on that date, along with the R version that is most recent as of that date.
  `electrify(mran_date = "2019-08-05", cran_like_url = NULL)`



If you have a reason that this won't work

**Comment by chasemc** [comment]
Feel free to reopen if for some reason the MRAN method isn't sufficient.
