### ISSUE TITLE
How to include png/html into app?

### ISSUE THREAD

**Issue by bianchenhao** [chasemc/electricShine#283]
I tried to put png/html into `inst/app/www` and use `tags$img(src = "www/my.png")` in the UI function, but it dosen't work in the app after installation.

**Comment by chasemc** [comment]
For future questions about Shiny I will defer you to post on sites like [stackoverflow.com](https://stackoverflow.com/) or [community.rstudio.com](https://community.rstudio.com/)

If you're unfamiliar with writing a shiny app as a package you can also try: [https://github.com/ThinkR-open/golem](https://github.com/ThinkR-open/golem)

For files located as you mentioned you need `tags$img(src = "app/www/my.png")`
