### ISSUE TITLE
An error in R 4.0.0

### ISSUE THREAD

**Issue by kaigu1990** [chasemc/electricShine#300]
Hi, 

There is an error related with R 4.0.0 when I try to deploy my demo following the document.
![image](https://user-images.githubusercontent.com/22772592/83389233-74953400-a422-11ea-9404-1bb3e3990d7f.png)
I think the reason is that electricShine can not be built in R 4.0.0
So could I use specific R version in electrify function?

Thank you !

**Comment by chasemc** [comment]
https://github.com/chasemc/electricShine/issues/255#issuecomment-610440946

**Comment by chasemc** [comment]
It looks like you are trying to build the app to be R 4.0.0 but currently have an older version than 4.0.0 installed on your machine. See the comment I referenced above

**Comment by kaigu1990** [comment]
Thanks!, it's ok now and resolves this issue for me
