### ISSUE TITLE
Support for building Mac apps

### ISSUE THREAD

**Issue by joekroese** [chasemc/electricShine#309]
Hi @chasemc, thanks for putting the time into developing this project. If I can get this working, it would perfectly complete my workflow for sharing apps with clients!

I use Mac OS and want to create apps for both Windows and Mac. There are two things I want to share:
1. a +1 (more like +999 😉) for adding support for building Mac apps. If you ever get round to this, it would be a major help to me.
2. In the meantime, can you think of any hacky solution for building electron apps for Mac?

**Comment by chasemc** [comment]
The documentation is outdated. The package should work for Mac as well
https://github.com/chasemc/electricShine/issues/272

**Comment by joekroese** [comment]
Brilliant news! I saw issue #272 but assumed I'd misunderstood something due to the documentation.
