### ISSUE TITLE
App hangs on loading - similar to #296 but fix doesn't work

### ISSUE THREAD

**Issue by py9mrg** [chasemc/electricShine#317]
I am not sure if I am having the same issue as @burtonrj had in #296, but my app is also hanging on the loading screen. I get an intermittent blue doughnut flashing indicating something is happening, but it never loads. This is even on the same machine as the one on which it was built. I also note that the processes remain in Task Manager after closing the app.

If I manually go into the app that is generated (i.e. into the build directory, dist, etc) and run the resulting RGui.exe, then load the package and use `run_app()` it works that way, so it seems to be something regarding the way electron is calling R, I guess.

I (think I) have everything set-up correctly in terms of the golem structure (it is working as a package, after all), and have also exported the app_ui and app_server functions too as per issue #296, but it still hangs on loading.

The Demo App runs fine.

I have checked very carefully the differences between my app and the Demo App and - apart from mine naturally being a bit more elaborate - nothing obvious is different. All other functions my app uses are exported too, just in case.

The only difference I can see is that golem must have made their `run_app` function a bit more complex at some point since the Demo App was made because the Demo App has the following:

```
#' Run the Shiny Application
#'
#' @param options optional, described in ?shiny::shinyApp
#' @param ... arguments to pass to golem_opts
#'
#' @export
run_app <- function(options = list()) {
  shinyApp(ui = app_ui,
           server = app_server,
           options = options) 
  
}
``` 

Whereas my app (from the golem template has):

```
#' Run the Shiny Application
#'
#' @param ... A series of options to be used inside the app.
#'
#' @export
#' @importFrom shiny shinyApp
#' @importFrom golem with_golem_options
run_app <- function(
  ...
) {
  with_golem_options(
    app = shinyApp(
      ui = app_ui, 
      server = app_server
    ), 
    golem_opts = list(...)
  )
}
```

However, changing my `run_app` to the same as Demo App doesn't fix it so, presumably this is a red herring. But then I can find nothing obviously different other than that.

**Comment by chasemc** [comment]
There are some issues with using the golem `run_app` as-is  (https://github.com/ThinkR-open/golem/pull/254)

Since the demo app `run_app` doesn't work, I'm leaning toward something happening with package dependencies (your app's `DESCRIPTION` file)

`electricShine` isolates itself at runtime 
https://github.com/chasemc/electricShine/blob/21f80d568bc04598368274ca89e81feb8dd42a5d/inst/template/src/background.js#L157-L166

 So even though you ran ` RGui.exe` from the build folder it is probably still using your regular R library. 

Check below for where additional logs should be written to:
https://github.com/chasemc/electricShine/blob/3a2fbadf51295c8de31c73d6637c6a73883a1516/inst/template/src/background.js#L51-L56

**Comment by py9mrg** [comment]
I did wonder about dependencies and have been through them as carefully as I can, I'm reasonably sure DESCRIPTION has got everything it needs (and NAMESPACE too). Checked the built app library folder and it *seems* to have installed all the dependencies it needs, assuming I haven't forgot something.

Thanks for the pointers, only log I could find was in the location you mentioned (Windows) and then `/logs/main.log`, and that just says...

```
[2020-06-26 13:34:40.916] [info] Application Started
[2020-06-26 13:37:14.738] [info] Application Started
[2020-06-26 14:01:51.176] [info] Application Started
[2020-06-26 14:06:09.256] [info] Application Started
[2020-06-26 14:19:39.012] [info] Application Started
[2020-06-26 14:35:41.313] [info] Application Started
[2020-06-26 15:22:21.301] [info] Application Started
[2020-06-26 15:42:58.037] [info] Application Started
```

Not much to go on! One thing I did notice after raising the issue was app_ui also starts a little differently with golem. It defines a param (`request`) they say not to remove as it's internal to shiny - but I've never needed it before so I did try removing it (!!!) but it still didn't fix the issue. One thing I haven't tried is both modifications (to app_ui and run_app) at the same time.

Anyway, I think what I'll have to do is massively simplify my app - probably de-golem it too and use a fresh R library - and see how I get on from there. Probably should have built it up more progressively in the first place, sorry. If I can't still fix it I'll put up a reprex here, but probably be after the weekend now. Thanks for the advice and have a nice weekend.

**Comment by chasemc** [comment]
`devtools::check()` will help finding issues with dependencies, etc

**Comment by py9mrg** [comment]
Thanks, yeah did the check and got it error and warning free before starting the app build.

**Comment by py9mrg** [comment]
Riiiiiiight, so I think I've finally got the problem - (maybe - it's now working on a streamlined version that had the problem so will have to put the full one back in to be sure). You were right, a dependency issue, but quite a subtle one, not captured by devtools (initially) and one that doesn't prevent `run_app` from working when loaded as a package.  The key was for me noticing a few of things.

1. You have shiny in Depends in DESCRIPTION, whereas I had it in Imports. I naively followed std advice about avoiding Depends (and golem template) and putting everything in Imports.
2. My code wasn't using `shiny::` etc everywhere because when it's in imports you don't need to to get the app working as a package - these dependencies and their functions load fine - but it clearly does affect it as an electricShine app.
3. If you don't `shiny::` everywhere, you **must** have shiny in Depends in DESCRIPTION **and** import it in NAMESPACE (it was only once I moved it to Depends that devtools started warning that I needed to import it too).

None of those cause a problem with the shiny app as an R package, but any one of those will prevent electricShine from loading the app properly after building. It took me [this](https://stackoverflow.com/a/49434070/3883341) answer on SO to *really* understand the difference between Depends and Imports in DESCRIPTION, and then devtools warning to know that *if* you use Depends then you should `@import` too. But, again, it doesn't affect general use so it was hard to realise this was the problem. And, even now, I don't fully understand why you have to put it in import in NAMESPACE *as well* as Depends in DESCRIPTION. More to learn yet, I guess.

For the record, I managed to work all this out after forking your demoApp and was going to use it as a basis for testing, but had the same loading issue. I then rolled back to the commit listed on the Get Started page (8426481) and that worked fine. In the latter commit you have removed shiny from imports in NAMESPACE, whereas it's still there in the previous one. Maybe this is just a Windows thing and the latest version works for you on linux/mac, but that definitely was the cause between the two versions for me.

So now I have to go back and either put every package I need in Depends in DESCRIPTION **and** import it in NAMESPACE, or to diligently use `::` everywhere. Hopefully it should work then. To be fair the general R advice is to use `::` everywhere, but I'm using the tidyverse a lot so I just imported dplyr, tibble, stringr etc to avoid having to do `::` all over the place! 

Anyway, thought that might help if anyone else has the same problem. I don't think it's urgent but could maybe do with a mention in the documentation that people need to either/or:

- Make sure they use `::` syntax for calling any functions (including shiny ones), and put the packages in Imports in DESCRIPTION
- Or, put the required packages in Depends of DESCRIPTION **and** make sure they're imported in NAMESPACE

In principle people should do the former option, but for a one off app the latter is a bit easier.

I can do this as a PR if you want? I realise people (including me!) should know all that anyway, but it's a bit of a subtlety that doesn't manifest in the vast majority of use cases - and the explanations why it matter are not always that clear/assume a lot of prior knowledge, hence me needing that specific SO comment to realise it.

So, I'm off to `::` all over my code and hope the full version will work!

**Comment by py9mrg** [comment]
...aaaaaand, have discovered even loading golem within the app causes the loading problem. For example, if I'm using the `run_app` function defined in demoApp (i.e. as per the first code block in my original comment) but have golem being loaded (e.g. import in NAMESPACE), *even if no golem functions are being used*, then the problem occurs. Presumably there is a conflict somewhere, although none are listed when manually loading either package in a fresh R session - seems like we have to, for the time being, avoid anything to do with golem.

But now I have a problem with trying to get gargle to authenticate so onto the next problem! Thanks for the pointers.
