### ISSUE TITLE
googlesheets4 / googledrive authentication

### ISSUE THREAD

**Issue by py9mrg** [chasemc/electricShine#318]
Me again (sorry!).

So I want each user of my app to be able to read/write google sheets to their google drive, but I'm having some trouble with authentication. Currently I have an "Authenticate" button that, when clicked, starts initiates the google authentication dance.

When running the app "normally" - i.e. before building into electron - a web browser opens, the auth dance happens, and everything is fine. After building to an electron app, nothing happens - the window gets a grey overlay and no web browser opens. Presumably this is an issue with electron not being able to trigger a web browser opening. I don't suppose there's an easy answer to this?

In principle there are workarounds with gargle, but none of them are very trivial and don't play nicely with my use case. I asked on the googledrive repo for an existing issue about whether they might consider support Google Drive File Stream as that would make auth issues in general a lot easier - gave electricShine a name check!

**Comment by chasemc** [comment]
It's probably not trivial, and not something I've attempted/I'm not the best person to ask.  Handling the creation of new windows is handled at the nodejs/electron level, so the easiest solution would be one that allows you to authenticate without opening a new browser window from Shiny.

Check the oauth stuff in the `httr ` package, especially:
https://support.rstudio.com/hc/en-us/articles/217952868-Generating-OAuth-tokens-for-a-server-using-httr

Hadley just put something up as well, I haven't looked too far into it:
https://gist.github.com/chasemc/2bab5f8c2ada2567115220f0c850efc9

If not, also maybe look into the `firebase` package

**Comment by py9mrg** [comment]
Thanks. Yeah I suspected it wouldn't be a simple solution. Have spent the morning looking through lots of gagrle, httr etc docs and it's *really* complicated, especially if (a) your company is like mine and doesn't allow service accounts/projects and (b) you want your colleagues to be using their own G Drive etc. Maybe it's simpler than I realise, but it's not clear at all to me right now! Thanks for thinking about it though, will close this.

**Comment by chasemc** [comment]
De check that first link though if you haven't, seems like it might work.

**Comment by py9mrg** [comment]
Yeah I'm on it now! Found it a while ago but have struggled to gt it to work for some reason - it keeps forcing a web browser to open even thought the example states it should provide a link (which would be a reasonable solution - a couple of manual copy and pastes is fine).

**Comment by py9mrg** [comment]
Ok so just an update for anyone with a similar issue. There is a solution but it's a bit hacky. For my unusual case, none of the non-interactive auth options listed by gargle work due to my company not being signed up to GCP so you can't manually make credentials first. Hopefully, longer term gargle will introduce a better method of dealing with this edge case - they actually used to have a better option as the first link provided by chasemc indicates, but they seem to have removed/changed that functionality now as it no longer prints out the url for manual copy/paste, which would have been great, but forces the web browser dance whatever options you choose - including out-of-band. 

Anyway, solution is listed as my closing comment in issue [148 here](https://github.com/r-lib/gargle/issues/148): just do a system call from the app to the R bundled in with your resulting app.
