### ISSUE TITLE
Reduce installer program capacity

### ISSUE THREAD

**Issue by jnhyeon** [chasemc/electricShine#320]
Thank you for making a good package.

In order to reduce the size of the installer, it is recommended that files not required for actual execution are not included in the installer.
(For example, help files and sample datasets included in most R packages.)

I hope the package will continue to be upgraded.
Thank you.

**Comment by chasemc** [comment]
Some files are removed for this purpose, see [here](https://github.com/chasemc/electricShine/blob/master/R/trim_r.R). I don't know if it's possible to separate sample datasets from data that is required for a package to function. If you have other suggestions, pull requests are welcome.
