### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by sebastianottmann** [chasemc/electricShine#349]
Thanks for the great package.

I currently have a problem: When I execute the function electrify() with my Shiny-App I don't get a folder "dist" in the buildPath.

It seems that there is a problem with "npm", here is the log file that is output when I set that the node.js I installed should be used:

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\nodejs\\node.exe',
> 1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'release',
> 1 verbose cli   '--scripts-prepend-node-path'
> 1 verbose cli ]
> 2 info using npm@6.14.4
> 3 info using node@v12.16.2
> 4 verbose stack Error: missing script: release
> 4 verbose stack     at run (C:\nodejs\node_modules\npm\lib\run-script.js:155:19)
> 4 verbose stack     at C:\nodejs\node_modules\npm\lib\run-script.js:63:5
> 4 verbose stack     at C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
> 4 verbose stack     at C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
> 4 verbose stack     at checkBinReferences_ (C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
> 4 verbose stack     at final (C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
> 4 verbose stack     at then (C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
> 4 verbose stack     at ReadFileContext.<anonymous> (C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:350:20)
> 4 verbose stack     at ReadFileContext.callback (C:\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:115:16)
> 4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:257:13)
> 5 verbose cwd C:\Users\***\Documents
> 6 verbose Windows_NT 10.0.17763
> 7 verbose argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release" "--scripts-prepend-node-path"
> 8 verbose node v12.16.2
> 9 verbose npm  v6.14.4
> 10 error missing script: release
> 11 verbose exit [ 1, true ]

Here is the log file if the package itself installs node.js:

> 
> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\R\\R-4.0.2\\library\\electricShine\\nodejs\\node-v12.16.2-win-x64\\node.exe',
> 1 verbose cli   'C:\\R\\R-4.0.2\\library\\electricShine\\nodejs\\node-v12.16.2-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'release',
> 1 verbose cli   '--scripts-prepend-node-path'
> 1 verbose cli ]
> 2 info using npm@6.14.4
> 3 info using node@v12.16.2
> 4 verbose stack Error: missing script: release
> 4 verbose stack     at run (C:\R\R-4.0.2\library\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\lib\run-script.js:155:19)
> 4 verbose stack     at C:\R\R-4.0.2\library\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\lib\run-script.js:63:5
> 4 verbose stack     at C:\R\R-4.0.2\library\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
> 4 verbose stack     at C:\R\R-4.0.2\library\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
> 4 verbose stack     at checkBinReferences_ (C:\R\R-4.0.2\library\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
> 4 verbose stack     at final (C:\R\R-4.0.2\library\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
> 4 verbose stack     at then (C:\R\R-4.0.2\library\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
> 4 verbose stack     at ReadFileContext.<anonymous> (C:\R\R-4.0.2\library\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\read-package-json\read-json.js:350:20)
> 4 verbose stack     at ReadFileContext.callback (C:\R\R-4.0.2\library\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:115:16)
> 4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:257:13)
> 5 verbose cwd C:\Users\***\Documents
> 6 verbose Windows_NT 10.0.17763
> 7 verbose argv "C:\\R\\R-4.0.2\\library\\electricShine\\nodejs\\node-v12.16.2-win-x64\\node.exe" "C:\\R\\R-4.0.2\\library\\electricShine\\nodejs\\node-v12.16.2-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "release" "--scripts-prepend-node-path"
> 8 verbose node v12.16.2
> 9 verbose npm  v6.14.4
> 10 error missing script: release
> 11 verbose exit [ 1, true ]

The error message also appears when I want to create the demoApp of the package. From my point of view it looks like npm can't find the script "release".

Is there a solution for this problem?

I work on the following system: Windows 10 / R 4.02

**Comment by hansduschke** [comment]
Similar here, running demoApp on Windows 8, R 4.02.
I get no dist folder too.

**npm log file:**

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\ag\\Documents\\R\\win-library\\4.0\\electricShine\\nodejs\\node-v12.16.2-win-x64\\node.exe',
1 verbose cli   'C:\\Users\\ag\\Documents\\R\\win-library\\4.0\\electricShine\\nodejs\\node-v12.16.2-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'release',
1 verbose cli   '--scripts-prepend-node-path'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle My_App@1.0.0~prerelease: My_App@1.0.0
6 info lifecycle My_App@1.0.0~release: My_App@1.0.0
7 verbose lifecycle My_App@1.0.0~release: unsafe-perm in lifecycle true
8 verbose lifecycle My_App@1.0.0~release: PATH: C:\Users\ag\Documents\R\win-library\4.0\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\.bin;C:\Users\ag\Documents\R\win-library\4.0\electricShine\nodejs\node-v12.16.2-win-x64;C:\Program Files\R\R-4.0.2\bin\x64;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\RStudio\bin\rpostback;C:\Program Files\RStudio\bin\postback
9 verbose lifecycle My_App@1.0.0~release: CWD: C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App
10 silly lifecycle My_App@1.0.0~release: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm test && webpack --config=build/webpack.app.config.js --env=production && electron-builder'
10 silly lifecycle ]
11 silly lifecycle My_App@1.0.0~release: Returned: code: 1  signal: null
12 info lifecycle My_App@1.0.0~release: Failed to exec release script
13 verbose stack Error: My_App@1.0.0 release: `npm test && webpack --config=build/webpack.app.config.js --env=production && electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\ag\Documents\R\win-library\4.0\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\ag\Documents\R\win-library\4.0\electricShine\nodejs\node-v12.16.2-win-x64\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid My_App@1.0.0
15 verbose cwd C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Users\\ag\\Documents\\R\\win-library\\4.0\\electricShine\\nodejs\\node-v12.16.2-win-x64\\node.exe" "C:\\Users\\ag\\Documents\\R\\win-library\\4.0\\electricShine\\nodejs\\node-v12.16.2-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "release" "--scripts-prepend-node-path"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error My_App@1.0.0 release: `npm test && webpack --config=build/webpack.app.config.js --env=production && electron-builder`
22 error Exit status 1
23 error Failed at the My_App@1.0.0 release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**R console output:**

`C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\bin\cli.js:93
				throw err;
				^

TypeError: merge is not a function
    at module.exports (C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\build\webpack.unit.config.js:22:10)
    at handleFunction (C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\bin\utils\prepareOptions.js:21:13)
    at prepareOptions (C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\bin\utils\prepareOptions.js:9:5)
    at requireConfig (C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\bin\utils\convert-argv.js:117:14)
    at C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\node_modules\yargs\yargs.js:576:18)
    at C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\ag\AppData\Local\Temp\RtmpKsJVsz\My_App\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! My_App@1.0.0 preunit: `webpack --config=build/webpack.unit.config.js --env=test --display=none`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the My_App@1.0.0 preunit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ag\AppData\Roaming\npm-cache\_logs\2020-08-17T11_07_46_987Z-debug.log
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! My_App@1.0.0 release: `npm test && webpack --config=build/webpack.app.config.js --env=production && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the My_App@1.0.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ag\AppData\Roaming\npm-cache\_logs\2020-08-17T11_07_47_052Z-debug.log
`

**Comment by chasemc** [comment]
see https://github.com/chasemc/electricShine/issues/343

Letting me know if that works will give me more confidence in merging it. I should have some time to work on this within the next week or so as well.

**Comment by hansduschke** [comment]
Many thanks, it works with the demoApp. This is such a cool package, just the right thing to deploy shiny apps to my audience, thanks a lot!

In case this provides some insights - running the demo - first, encountered an error `enoent ENOENT: no such file or directory, open '*\\package.json', where * is the current R working directory. After setwd() to path on the HD with build_path, it worked.

However, I can not get my own shiny app running. 

Building and all works, but running the exe I get: 

`JavaScript error - uncaught exceptions
read.ECONNRESET
at TCP.onStreamRead(internal/stream_base_commons.js:200:27`

Then stuck on loading screen, after exit exe somehow keeps running in the background.

Not sure how to debug this, I am completely new to electron. My package is bare-bones and works (devtools::install(); packagename::run_app()), DESCRIPTION reads

`LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
Depends:
    shiny,
    ggplot2,
    stringr,
    dplyr,
    R (>= 3.5)`

I also have a dataset in the package at data/

Could you please point me in the right direction what the problem might be? Cheers!

**Comment by sebastianottmann** [comment]
Thank you for your answer!

I have completely uninstalled the package and reloaded it with remotes::install_github("chasemc/electricShine@webpackmerge-fix")

Unfortunately the same error still occurs:

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\nodejs\\node.exe',
> 1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'release',
> 1 verbose cli   '--scripts-prepend-node-path'
> 1 verbose cli ]
> 2 info using npm@6.14.4
> 3 info using node@v12.16.2
> 4 verbose stack Error: missing script: release
> 4 verbose stack     at run (C:\nodejs\node_modules\npm\lib\run-script.js:155:19)
> 4 verbose stack     at C:\nodejs\node_modules\npm\lib\run-script.js:63:5
> 4 verbose stack     at C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
> 4 verbose stack     at C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
> 4 verbose stack     at checkBinReferences_ (C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
> 4 verbose stack     at final (C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
> 4 verbose stack     at then (C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
> 4 verbose stack     at ReadFileContext.<anonymous> (C:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:350:20)
> 4 verbose stack     at ReadFileContext.callback (C:\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:115:16)
> 4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:257:13)
> 5 verbose cwd C:\Users\\***\Documents
> 6 verbose Windows_NT 10.0.17763
> 7 verbose argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release" "--scripts-prepend-node-path"
> 8 verbose node v12.16.2
> 9 verbose npm  v6.14.4
> 10 error missing script: release
> 11 verbose exit [ 1, true ]

The error message also appears when I use the demoApp.

Is there still information needed for error handling?

**Comment by sebastianottmann** [comment]
I had been able to create the DemoApp in a previous version of the package. Now I deleted the "dist" folder and tried to create it again with "run_build_release". I get the same error message again that the script release is missing.

Is there already a solution for the problem or an idea what this could be? I would like to use the package in a project of mine, because the creation of a standalone app is very important.

**Comment by BenWiseman** [comment]
Ack, just got around the local install error (passing in package name as argument in electrify() rather than trying to use install_user_app() (IDK what's going on in that function). 

`...\node_modules\webpack-cli\bin\cli.js:93` 
`throw err;`
`TypeError: merge is not a function`

**Comment by py9mrg** [comment]
> see [#343 (comment)](https://github.com/chasemc/electricShine/issues/343#issuecomment-669926649)
> 
> Letting me know if that works will give me more confidence in merging it. I should have some time to work on this within the next week or so as well.

@chasemc Worked perfectly for me. Although I note there's a recent PR that makes similar changes in multiple places so maybe some of the people who it didn't work for need those other changes too.
