### ISSUE TITLE
Install from local not working

### ISSUE THREAD

**Issue by BenWiseman** [chasemc/electricShine#368]
`Finshed: Installing your Shiny package into electricShine framework
Error in system.file("extdata", "icon", package = my_package_name, lib.loc = library_path) : 
  'package' must be of length 1`

I could just be not understanding the documentation, but it seems like local install isn't passing through the package path from `local_package_path` or something.

**Comment by BenWiseman** [comment]
Here is where it breaks:

`
    my_package_name <- electricShine::install_user_app(library_path = library_path ,
                                                       repo_location = "local",
                                                       repo = local_package_path,
                                                       repos = cran_like_url,
                                                       package_install_opts = package_install_opts)
  }
  
  
  
  # Transfer icons if present -----------------------------------------------
  
  
  electron_build_resources <- system.file("extdata", 
                                          "icon",
                                          package = my_package_name,
                                          lib.loc = library_path)`


Because `electricShine::install_user_app` can only return a NULL as it just gives the result of readLines() on a newly created tempfile? 

I'm happy to help make this thing a reality, but, the code in install_user_app is really confusing. Like, are all of the environment variables just being used to prevent you from having to pass variables between functions?

**Comment by davidbudzynski** [comment]
I am having the very same issue as described by @BenWiseman

**Comment by marecabo** [comment]
I solved this issue for me with properly installing `rlang` from source in my base R installation (outside the renv) environment. RTools was also in my path. 

After also specifying a custom `nodejs_path` as argument (see https://github.com/chasemc/electricShine/blob/6f53a08a37af43db097c412591f5ed7a689a2cc8/R/meta_function.R#L44 maybe related: https://github.com/chasemc/electricShine/issues/308), it ran further and I encountered https://github.com/chasemc/electricShine/issues/343 for which a not-yet-merged fix exists. 

With that, the demo app starts but loads indefinitely (see https://github.com/chasemc/electricShine/issues/343#issuecomment-689011641 and following) and this error message appears:

```log
A JavaScript Error occurred in the main process

Uncaught exception:
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
```

**Comment by Wladimir-Sanyer** [comment]
Alguna solución? El problema persiste y no deja realizar la aplicación con normalidad

**Comment by Wladimir-Sanyer** [comment]
any solution? the problem persists and does not allow the application to be carried out normally

**Comment by chasemc** [comment]
I'm planning to work on the package in the next couple weeks. My assumption is that @marecabo is correct. Using electricShine from renv is likely to cause issues
