### ISSUE TITLE
Error during WebSocket handshake ERR_INVALID_HTTP_RESPONSE

### ISSUE THREAD

**Issue by tomicapretto** [chasemc/electricShine#382]
Hi, 

I have a medium sized app that now has its installable thanks to this package. 

However, sometimes when I run the executable, the app crashes and the browser console shows the ERR_INVALID_HTTP_RESPONSE error. This also causes the TypeError seen in the attached image. 

I guess this could be fixed by changing some parameters in the `src/background.js` folder, but since I am not very familiar with JS and web technologies, I'm not sure about it. 

Does anybody know what could be the cause of this problem and any hints on how to fix it? 

Thank you all

![error-shiny](https://user-images.githubusercontent.com/25507629/96539502-8eb89d00-1271-11eb-9432-8209d6b81344.PNG)

NOTE: I've already fixed the problem related to the NA parsing listed in the image and it is not connected to the bigger problem reported here.

**UPDATE**

This usually happens when there are more than one attempts to connect to the app like here

![image](https://user-images.githubusercontent.com/25507629/96540132-38e4f480-1273-11eb-8f77-76862a7e8636.png)

**Comment by tomicapretto** [comment]
I've been on this problem for some hours and *I think* the problem is caused because of the calls  `mainWindow.loadURL('http://127.0.0.1:' + srv.address().port);` within the for loop referenced below

I ended up refactoring the  entire `background.js` file and I'm using a `while` instead of a `for` loop. Now, with the `.loadURL()` call outside the loop, my app does not crash anymore (even if it tries several times).

This is the part of `background.js` I'm referencing 

https://github.com/chasemc/electricShine/blob/f4f8c3f0f3bc2ffa6d3f33bf60637a1595656585/inst/template/src/background.js#L174-L182

**Comment by chasemc** [comment]
We've seen the TypeError response before https://github.com/chasemc/electricShine/issues/103#issuecomment-532054448 and it's also occurred in other shiny/htmlwidgets project and is usually related to conflicting js or css dependencies... although you do say the app works sometimes.

Changing to `for` to `while` only means electron will indefinitely try to connect until successful. I'm wondering if it's a result of the Shiny app taking a long time to load?

**Comment by tomicapretto** [comment]
I ended up modifying the `background.js` script a lot. The last problem I had was that Electron sometimes wouldn't load the URL at first try. I ended up placing a "Click here if app doesn't load" link referencing the URL where the app was being hosted and that solved the problem. I can share the script if you want to see how it works.

**Comment by chasemc** [comment]
Thanks, yeah it might be worth moving the await so there's an initial pause.
