### ISSUE TITLE
How to access shiny log message

### ISSUE THREAD

**Issue by gdurif** [chasemc/electricShine#401]
Hi,
I have a question regarding the standalone app once it is built, installed and running. My shiny app prints some message in the R console to help debugging.
How could I access the console output from the standalone app ?
Thanks

**Edit 1** : maybe through the option list of the `run_app` function ?

**Edit 2** : if not possible through electricShine, I'll end up doing this https://stackoverflow.com/questions/47331814/r-shiny-output-to-external-file in the function `run_app`

**Comment by monkeychex3** [comment]
I found it useful to use `npm start` to open my app, so I could see the log in the shell I used to open it

**Comment by gdurif** [comment]
Eventually, I rewrited the app launcher to bypass the `js` part and run it directly from a batch script.

**Comment by chasemc** [comment]
Should be here:
https://github.com/chasemc/electricShine/blob/7a2a2fc6f13f91157ea7bee14279b98df393be7d/inst/template/src/background.js#L51-L54
