### ISSUE TITLE
shinyApp not found in demoApp

### ISSUE THREAD

**Issue by monkeychex3** [chasemc/electricShine#410]
![image](https://user-images.githubusercontent.com/42021035/101838247-49487b80-3b0e-11eb-9efc-b3a724fbb971.png)

I'm on Win10, using R 4.0.2 and I had to use `remotes::install_github("chasemc/electricShine@webpackmerge-fix")` to get rid of "merge" error

I got the demoApp to `electrify()` from the github repo with
```
electricShine::electrify(app_name = "demoApp",
    short_description = "words description",
    semantic_version = "1.0.0",
    build_path = build_path,
    function_name = "run_app",
    git_host = "github",
    git_repo = "chasemc/demoApp",
    package_install_opts = list(type = "binary",
        dependencies = c("Depends", 
            "Imports")
    ),
    cran_like_url = "https://cran.r-project.org"
)
```

I tried running the "\~/dist/win-unpacked/demoApp.exe" and felt like it was infinitely loading. I closed it and instead ran "\~/dist/demoApp Setup 1.0.0.exe" where it seemed like the install went fine until I again got to an infinite loading screen.

To inspect further, I went to the build "demoApp" folder, ran `npm start`, and then I saw the included picture from behind the loading screen. Am I doing something wrong?

**Comment by steweiss** [comment]
I am running into the same loading screen problem.
I tried the reference code and it does not work. I also looked through folders if I can find the shiny code and it is not copied as far as I see.

**Comment by chasemc** [comment]
Update:
https://github.com/chasemc/electricShine/projects
